server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: healthcheck
  static_configs:
  - targets:
      - localhost
    labels:
      job: mattermostlog
      __path__: /mnt/support_logs/*.log
  pipeline_stages:
  - regex:
      expression: '^(?P<level>\S+)\s+\[(?P<time>.*)\](?P<msg>.*)caller="(?P<caller>\S+)".*$'
  - labels:
      level:
      msg:
      caller:
  - timestamp:
      source: time
      format: 2006-01-02 15:04:05.000 -07:00
