server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: healthcheck
  static_configs:
  - targets:
      - localhost
    labels:
      job: mattermostlog
      __path__: /mnt/support_logs/*.log
  pipeline_stages:
  - regex:
      expression: "^(?P<level>\\S+)\\s+ \\[(?P<timestamp>.*)\\] caller=\"(?P<caller>\\S+)\" worker=(?P<worker>\\S+) (?P<details>.*)$"
  - timestamp:
      source: timestamp
      format: "RFC3339Nano"
  - labels:
      msg:
      level:
      caller:
